/**
 * Utility to extract media file paths from tool output text.
 * Used to detect images and HTML charts generated by Python scripts.
 */

const IMAGE_EXTENSIONS = new Set(['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp']);
const HTML_EXTENSIONS = new Set(['html', 'htm']);

export type MediaType = 'image' | 'plotly_html';
export type Confidence = 'high' | 'medium' | 'low';

export interface ExtractedMedia {
  path: string;
  type: MediaType;
  confidence: Confidence;
  extension: string;
}

/**
 * Patterns for detecting file paths in tool output.
 * Each pattern captures the file path in group 1.
 */
const DETECTION_PATTERNS: { pattern: RegExp; confidence: Confidence }[] = [
  // Explicit save messages (highest confidence)
  {
    pattern:
      /(?:saved|exported|written|generated|created|saving|writing)\s+(?:to|as|:)?\s*['"]?([^\s'"<>]+\.(?:png|jpg|jpeg|gif|svg|webp|html|htm))['"]?/gi,
    confidence: 'high'
  },
  // plt.savefig() / fig.savefig() output
  {
    pattern:
      /(?:plt|fig|figure)\.savefig\s*\(\s*['"]([^'"]+\.(?:png|jpg|jpeg|gif|svg))['"]?\s*\)/gi,
    confidence: 'high'
  },
  // Plotly write_html
  {
    pattern: /(?:fig|figure)\.write_html\s*\(\s*['"]([^'"]+\.html?)['"]?\s*\)/gi,
    confidence: 'high'
  },
  // Output file indicator
  {
    pattern:
      /(?:output|figure|chart|plot|graph|image)\s*(?:file)?[:\s]+['"]?([^\s'"<>]+\.(?:png|jpg|jpeg|gif|svg|webp|html|htm))['"]?/gi,
    confidence: 'medium'
  },
  // Relative paths starting with ./
  {
    pattern:
      /(?:^|[\s'"(])(\.[/\\][^\s'"<>()]+\.(?:png|jpg|jpeg|gif|svg|webp|html|htm))(?:$|[\s'")\]])/gim,
    confidence: 'medium'
  },
  // Absolute paths on macOS/Linux (only within agent directory context)
  {
    pattern:
      /(?:^|[\s'"(])(\/(?:Users|home|tmp|var)[^\s'"<>()]*\.(?:png|jpg|jpeg|gif|svg|webp|html|htm))(?:$|[\s'")\]])/gim,
    confidence: 'low'
  },
  // Simple filename pattern (lowest confidence)
  {
    pattern:
      /(?:^|[\s'"(])([a-zA-Z0-9_-]+\.(?:png|jpg|jpeg|gif|svg|webp|html|htm))(?:$|[\s'")\]])/gim,
    confidence: 'low'
  }
];

/**
 * Get file extension from path
 */
function getExtension(path: string): string {
  const parts = path.split('.');
  return parts.length > 1 ? parts.pop()!.toLowerCase() : '';
}

/**
 * Determine media type from extension
 */
function getMediaType(extension: string): MediaType {
  if (HTML_EXTENSIONS.has(extension)) {
    return 'plotly_html';
  }
  return 'image';
}

/**
 * Normalize path - remove surrounding quotes and resolve ./
 */
function normalizePath(path: string): string {
  return path.replace(/^['"]|['"]$/g, '').replace(/^\.\//, '');
}

/**
 * Check if the extension is supported
 */
function isSupportedExtension(extension: string): boolean {
  return IMAGE_EXTENSIONS.has(extension) || HTML_EXTENSIONS.has(extension);
}

/**
 * Extract media file paths from tool output text.
 *
 * @param output - The tool output text to parse
 * @returns Array of extracted media items, deduplicated and sorted by confidence
 */
export function extractMediaPaths(output: string): ExtractedMedia[] {
  if (!output || typeof output !== 'string') {
    return [];
  }

  const results = new Map<string, ExtractedMedia>();

  for (const { pattern, confidence } of DETECTION_PATTERNS) {
    // Reset lastIndex for global patterns
    pattern.lastIndex = 0;

    let match: RegExpExecArray | null;
    while ((match = pattern.exec(output)) !== null) {
      const rawPath = match[1];
      if (!rawPath) continue;

      const path = normalizePath(rawPath);
      const extension = getExtension(path);

      if (!isSupportedExtension(extension)) continue;

      // Only keep highest confidence match for each path
      const existing = results.get(path);
      if (!existing || getConfidenceScore(confidence) > getConfidenceScore(existing.confidence)) {
        results.set(path, {
          path,
          type: getMediaType(extension),
          confidence,
          extension
        });
      }
    }
  }

  // Sort by confidence (high -> medium -> low)
  return Array.from(results.values()).sort(
    (a, b) => getConfidenceScore(b.confidence) - getConfidenceScore(a.confidence)
  );
}

/**
 * Convert confidence to numeric score for sorting
 */
function getConfidenceScore(confidence: Confidence): number {
  switch (confidence) {
    case 'high':
      return 3;
    case 'medium':
      return 2;
    case 'low':
      return 1;
  }
}

/**
 * Check if the output likely contains visualization-related content
 */
export function hasVisualizationKeywords(output: string): boolean {
  const keywords = [
    'savefig',
    'write_html',
    'matplotlib',
    'plotly',
    'seaborn',
    'chart',
    'plot',
    'graph',
    'figure',
    'visualization'
  ];
  const lowerOutput = output.toLowerCase();
  return keywords.some((keyword) => lowerOutput.includes(keyword));
}
